# Generated by Django 3.1.1 on 2020-10-05 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Block_Name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='floors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Floor_Number', models.IntegerField(null=True)),
                ('Number_of_Rooms', models.IntegerField(null=True)),
                ('Block_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostelapp.blocks')),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_No', models.IntegerField(null=True)),
                ('Capacity', models.IntegerField(null=True)),
                ('Cost', models.BigIntegerField(null=True)),
                ('Number_already_occupied', models.IntegerField(null=True)),
                ('Block_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostelapp.blocks')),
                ('Floor_Number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostelapp.floors')),
            ],
        ),
        migrations.CreateModel(
            name='warden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Warden_ID', models.CharField(max_length=20, null=True)),
                ('Name', models.CharField(max_length=20, null=True)),
                ('Gender', models.CharField(max_length=6, null=True)),
                ('DOB', models.DateField(null=True)),
                ('Phone_Number', models.BigIntegerField(null=True)),
                ('Block_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostelapp.blocks')),
                ('Floor_Number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostelapp.floors')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reg_No', models.CharField(max_length=20, null=True)),
                ('Name', models.CharField(max_length=20, null=True)),
                ('Phone_Number', models.BigIntegerField(null=True)),
                ('DOB', models.DateField(null=True)),
                ('Gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostelapp.blocks')),
                ('Room_No', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostelapp.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='Warden_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostelapp.warden'),
        ),
    ]
