# Generated by Django 3.1.3 on 2020-11-25 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0002_auto_20201115_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='Warden_ID',
        ),
        migrations.AddField(
            model_name='room',
            name='Warden_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostelapp.warden'),
        ),
    ]
