# Generated by Django 3.1.3 on 2020-11-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0003_auto_20201125_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
