# Generated by Django 3.1.3 on 2020-12-18 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostelapp', '0004_room_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_room',
            name='user',
            field=models.OneToOneField(limit_choices_to={'groups__name': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
