# Generated by Django 3.1.3 on 2021-03-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0006_gatepass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatepass',
            old_name='outing_data',
            new_name='outing_date',
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='applied_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
