# Generated by Django 3.1.3 on 2021-03-01 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0008_auto_20210301_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatepass',
            name='user',
        ),
    ]
