# Generated by Django 3.1.3 on 2021-03-01 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0009_remove_gatepass_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostelapp.student_room'),
            preserve_default=False,
        ),
    ]
