# Generated by Django 3.1.3 on 2021-03-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0012_auto_20210301_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='approval_status',
            field=models.BooleanField(null=True),
        ),
    ]
