# Generated by Django 3.1.3 on 2021-03-02 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0013_gatepass_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='applied_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
