# Generated by Django 3.1.3 on 2021-03-02 14:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0014_gatepass_applied_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='Warden_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostelapp.warden'),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='applied_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
