# Generated by Django 3.1.3 on 2021-03-02 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostelapp', '0015_auto_20210302_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatepass',
            name='Warden_id',
        ),
        migrations.AddField(
            model_name='gatepass',
            name='Warden_Id',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'warden'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sso', to=settings.AUTH_USER_MODEL),
        ),
    ]
