# Generated by Django 3.1.3 on 2021-03-02 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0016_auto_20210302_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatepass',
            name='Warden_Id',
        ),
        migrations.AddField(
            model_name='gatepass',
            name='Warden_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostelapp.room'),
        ),
    ]
