# Generated by Django 3.1.3 on 2021-03-02 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0017_auto_20210302_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='Warden_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostelapp.warden'),
        ),
    ]
