# Generated by Django 3.1.3 on 2021-03-08 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostelapp', '0018_auto_20210302_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='issue_raiser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('user', models.OneToOneField(limit_choices_to={'groups__name': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='issue_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField()),
                ('issueid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelapp.issue_raiser')),
            ],
        ),
    ]
