# Generated by Django 3.1.3 on 2021-03-08 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostelapp', '0019_issue_raiser_issue_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue_student',
            name='user',
            field=models.OneToOneField(limit_choices_to={'groups__name': 'student'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
