# Generated by Django 3.1.3 on 2021-03-08 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostelapp', '0023_auto_20210308_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue_student',
            name='downvote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issue_student',
            name='issueid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelapp.issue_raiser'),
        ),
        migrations.AlterField(
            model_name='issue_student',
            name='upvote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issue_student',
            name='user',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'student'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
        ),
    ]
