# Generated by Django 3.1.3 on 2021-03-09 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0024_auto_20210308_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_student',
            name='issueid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostelapp.issue_raiser'),
        ),
    ]
