# Generated by Django 3.1.7 on 2021-04-26 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hostelapp', '0025_auto_20210309_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendence_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetaken', models.DateTimeField()),
                ('warden', models.ForeignKey(limit_choices_to={'groups__name': 'warden'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='students_attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostelapp.attendence_date')),
                ('room_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostelapp.room')),
                ('student_name', models.ForeignKey(limit_choices_to={'groups__name': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
